import {_electron as electron} from '@playwright/test';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {fixture,timedBubbles} from './fixtures.mjs';
import {checkTimedBubbles} from './bubbles-ui.mjs';
import {checkStillReading} from './stills-ui.mjs';
import {checkPrecacheTransition} from './transitions-ui.mjs';
import {checkJoinedSequence} from './sequence-ui.mjs';
const root=await fs.mkdtemp(path.join(os.tmpdir(),'manga-ui-')),checkout=fileURLToPath(new URL('../..',import.meta.url));let app;
try{
 const {service,project,profile}=await fixture(root);await timedBubbles(project,service);const book=await service.open(project);
 app=await electron.launch({args:['--no-sandbox','--ozone-platform=x11','--disable-gpu',checkout],env:{...process.env,FUNCIV_USER_DATA:profile,CIVITAI_API_TOKEN:''},timeout:45000});
 let page=app.windows().find(p=>p.url().includes('index.html'));if(!page)page=await app.waitForEvent('window',{predicate:p=>p.url().includes('index.html'),timeout:30000});
 await page.setViewportSize({width:1450,height:1000});const errors=[];page.on('pageerror',e=>{errors.push(e.stack||e.message);console.error('MANGA PAGE ERROR',e.stack||e.message);});page.on('dialog',d=>d.accept());
 await page.waitForFunction(()=>!!window.app?.navBar?._el);const lang=page.locator('.language-prompt__btn[data-locale=en]');if(await lang.isVisible())await lang.click({force:true});
 await page.locator('[data-view-id=manga]').click();await page.locator('.mg [data-field=recent]').selectOption('h3:'+book.id);await page.waitForFunction(()=>window.app.manga.book?.pages.length===2);
 assert.equal(await page.locator('.mg-hotspot').count(),0,'page with no panels remains readable');assert.equal(await page.locator('.mg-page-image').evaluate(i=>i.naturalWidth),320);
 await checkStillReading(page,project);
 await checkPrecacheTransition(page);
 await page.locator('.mg [data-action=next-page]').click();await page.locator('.mg-hotspot').first().click();await page.waitForFunction(()=>window.app.manga.player.running&&window.app.manga.player.position>100);
 await page.evaluate(()=>{const p=window.app.manga.player;window.mangaProbe=p.audioContext.createAnalyser();p.gains[p.active].connect(window.mangaProbe);});await page.waitForFunction(()=>{const a=new Float32Array(2048);window.mangaProbe.getFloatTimeDomainData(a);return a.some(n=>Math.abs(n)>.001);});
 await page.evaluate(()=>{window.mangaBackgroundPlays=0;const v=window.app.videoPlayer,toggle=v.togglePlay.bind(v);v.togglePlay=()=>{window.mangaBackgroundPlays++;return toggle();};});await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>window.mangaBackgroundPlays),0,'Manga shortcuts cannot start the background player');assert.equal(await page.evaluate(()=>window.app.manga.player.intent),false);const state=await page.evaluate(()=>({time:window.app.manga.player.position,src:window.app.manga.player.video.currentSrc}));
 await page.locator('.mg [data-field=bubbles]').uncheck();assert.equal(await page.locator('.mg-bubbles').isVisible(),false);assert.equal(await page.evaluate(()=>window.app.manga.player.video.currentSrc),state.src);
 await page.locator('.mg [data-field=seek]').fill('1200');await page.locator('.mg [data-field=seek]').dispatchEvent('change');await page.waitForFunction(()=>!window.app.manga.player.switching&&Math.abs(window.app.manga.player.position-1200)<80);
 await page.locator('.mg [data-field=seek]').fill('300');await page.locator('.mg [data-field=seek]').dispatchEvent('change');await page.waitForFunction(()=>!window.app.manga.player.switching&&Math.abs(window.app.manga.player.position-300)<80);
 await page.locator('.mg [data-field=bubbles]').check();assert.equal(await page.locator('.mg-bubbles').isVisible(),true);
 await checkTimedBubbles(page);
 await page.locator('.mg [data-action=fullscreen]').click();await page.waitForFunction(()=>!!document.fullscreenElement);await page.keyboard.press('f');await page.waitForFunction(()=>!document.fullscreenElement);
 await page.locator('.mg-header [data-action=details]').click();await page.locator('.mg [data-setting=extraSeconds]').fill('1');await page.locator('.mg [data-setting=extraSeconds]').dispatchEvent('change');await page.locator('.mg [data-setting=mode]').selectOption('extend');await page.locator('.mg [data-action=play]').click();await page.waitForFunction(()=>window.app.manga.player.segment?.kind==='extension'&&window.app.manga.player.running,{},{timeout:12000});
 assert.equal(await page.evaluate(()=>window.app.manga.player.video.paused),true);await page.locator('.mg [data-action=stop]').click();assert.equal(await page.evaluate(()=>window.app.manga.player.wrapper.paused),true);
 await page.locator('.mg [data-action=back]:visible').click();await page.locator('.mg [data-setting=mode]').selectOption('loop');await page.locator('.mg-hotspot').first().click();await page.waitForFunction(()=>!window.app.manga.player.switching&&window.app.manga.player.running&&window.app.manga.player.segment?.kind==='loop',{},{timeout:12000});assert.equal(await page.evaluate(()=>window.app.manga.player.video.muted),true);
 await page.locator('.mg [data-action=stop]').click();await page.locator('.mg [data-action=inline]').click();await page.locator('.mg [data-field=bubbles]').uncheck();assert.equal(await page.locator('.mg video').count(),2,'toggling presentation keeps the playback elements');
 await fs.mkdir('/tmp/funciv-manga-screenshots',{recursive:true});await page.screenshot({path:'/tmp/funciv-manga-screenshots/reader.png'});
 await page.locator('.mg [data-action=back]:visible').click();await page.locator('.mg [data-action=bookmark]').click();assert.ok((await page.locator('.mg [data-action=bookmark]').textContent()).includes('Bookmarked'));
 await page.locator('.mg-close-details').click();await page.setViewportSize({width:620,height:900});await page.screenshot({path:'/tmp/funciv-manga-screenshots/reader-narrow.png'});
  await page.locator('.mg [data-field=layout]').selectOption('scroll');await page.locator('.mg [data-action=zoom-in]').click();
 await page.locator('.mg [data-setting=ignoreBubbleTiming]').check();
 await page.evaluate(async()=>{const c=window.app.manga,s=c.root.querySelector('.mg-surface');s.scrollTop=180;await c.save();const book=await c.job('reopen',{id:c.book.id});await c.accept(book,{persistCurrent:false});});
 assert.equal(await page.locator('.mg [data-field=layout]').inputValue(),'scroll');assert.equal(await page.locator('.mg-focus').isVisible(),false,'returning to a saved page does not force panel focus');assert.ok(await page.locator('.mg-surface').evaluate(s=>s.scrollTop>100));
 assert.equal(await page.locator('.mg [data-setting=ignoreBubbleTiming]').isChecked(),true,'bubble timing preference survives reopening the book');
 await checkJoinedSequence(page,project);
 await page.evaluate(async()=>{const c=window.app.manga;await c.page(0);c.tick({segment:c.player.segment,position:c.player.position,playing:false,running:false});});assert.equal(await page.evaluate(()=>window.app.manga.panelId),null,'previous page cannot restore a stale selected panel');
 await page.locator('.mg [data-action=next-page]').click();
 await page.evaluate(async()=>{const c=window.app.manga,run=await c.ipc('prepare',{id:c.book.id,page:1,settings:c.settings,overrides:c.overrides}),ipc=c.ipc.bind(c);window.mangaCancellationRun=run;c.run=null;c.ipc=(a,p)=>a==='prepare'?new Promise(resolve=>{window.finishMangaPrepare=()=>resolve(run);}):ipc(a,p);window.pendingMangaFocus=c.focusPanel(c.book.pages[1].panels[0].id,1);});await page.waitForFunction(()=>!!window.finishMangaPrepare);
 await page.locator('[data-view-id=composer]').click();await page.evaluate(async()=>{window.finishMangaPrepare();await window.pendingMangaFocus;});assert.equal(await page.evaluate(()=>window.app.manga.player.intent),false);assert.equal(await page.evaluate(()=>window.app.manga.devices.active),false);
 await page.locator('[data-view-id=manga]').click();await page.evaluate(()=>{const c=window.app.manga,run=window.mangaCancellationRun,load=c.player.load.bind(c.player);c.run=run;c.player.load=(...args)=>new Promise(resolve=>{window.finishMangaLoad=async()=>{await load(...args);resolve();};});window.pendingMangaLoad=c.focusPanel(c.book.pages[1].panels[0].id,1);});await page.waitForFunction(()=>!!window.finishMangaLoad);
 await page.locator('[data-view-id=composer]').click();await page.evaluate(async()=>{await window.finishMangaLoad();await window.pendingMangaLoad;});assert.equal(await page.evaluate(()=>window.app.manga.player.intent),false,'late decoding cannot start playback after leaving Manga');
 assert.deepEqual(errors,[]);console.log('PASS Manga Electron: source import, page images, playback, bubbles, seek both directions, motion extension, loops, bookmarks, narrow layout, source release.');
}catch(error){console.error(error);throw error;}finally{if(app){app.process().kill('SIGTERM');await app.close().catch(()=>{});}await fs.rm(root,{recursive:true,force:true});}
