// Real Electron smoke test. All media are synthesized in /tmp; no devices or
// account credentials are configured. Run: node tests/composer/smoke.mjs
import { _electron as electron } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ComposerService } from '../../electron/composer-service.cjs';
import { checkTimelineEditing, chooseSectionFolders, checkLargeLibrary } from './timeline-ui.mjs';

const checkout=fileURLToPath(new URL('../..',import.meta.url));
const root=await fs.mkdtemp(path.join(os.tmpdir(),'funciv-electron-'));
const userData=path.join(root,'profile'),library=path.join(root,'clips','Pulse');await fs.mkdir(library,{recursive:true});
const service=await new ComposerService(path.join(userData,'composer')).init();
const signal=new AbortController().signal;let app;
try{
  for(const [name,color,size] of [['A','teal','320x180'],['B','purple','180x320'],['C','gray','160x160']]){
    await service.run('ffmpeg',['-v','error','-f','lavfi','-i',`color=c=${color}:s=${size}:r=30:d=2`,'-vf','drawbox=x=(iw-50)/2:y=(ih-50)/2:w=50:h=50:color=white:t=fill','-an','-c:v','libx264','-pix_fmt','yuv420p','-threads','1',path.join(library,`${name}.mp4`)],signal);
    if(name!=='C')await fs.writeFile(path.join(library,`${name}.funscript`),JSON.stringify({actions:Array.from({length:9},(_,i)=>({at:i*250,pos:i%2?90:10}))}));
  }
  await service.run('ffmpeg',['-v','error','-f','lavfi','-i','sine=frequency=220:duration=6','-af',"volume='0.5+0.5*sin(4*PI*t)':eval=frame",path.join(root,'Preview song.wav')],signal);
  await service.scan(path.join(root,'clips'),signal);const song=await service.importSong(path.join(root,'Preview song.wav'),signal);
  await service.tag(service.catalog.clips.find(c=>c.name==='B.mp4').id,'Flow');
  service.catalog.clips.push({id:'synthetic-remote',name:'Remote fixture',origin:'dataset',quality:5,review_status:'approved',available:false,duration_ms:2000,categories:['Pulse']});await service.saveCatalog();
  service.catalog.clips.push({...structuredClone(service.catalog.clips.find(c=>c.name==='A.mp4')),id:'synthetic-draft',name:'Draft fixture',origin:'dataset',quality:5,review_status:'draft',audio_sync:true,categories:['Draft','Alternate'],dataset_categories:['Draft','Alternate'],automatic_categories:['Draft','Alternate'],category_paths:['Season/Draft','Season/Alternate'],commit:'a'.repeat(40),variant_id:'b'.repeat(64)});
  service.catalog.clips.push({id:'synthetic-unrated-draft',name:'Unrated draft fixture',origin:'dataset',quality:0,review_status:'draft',available:false,duration_ms:2000,categories:['Draft']});
  await service.saveCatalog();
  app=await electron.launch({args:['--no-sandbox','--disable-gpu','--disable-frame-rate-limit','--disable-gpu-vsync',checkout],env:{...process.env,FUNCIV_USER_DATA:userData,CIVITAI_API_TOKEN:''},timeout:45000});
  const page=app.windows().find(p=>p.url().includes('index.html'))||await app.waitForEvent('window',{predicate:page=>page.url().includes('index.html'),timeout:30000}).catch(async()=>app.windows().find(p=>p.url().includes('index.html')));
  assert.ok(page,'main window opens');await page.setViewportSize({width:1500,height:1080});
  const until=async(fn,{timeout=30000}={})=>{const end=Date.now()+timeout;while(Date.now()<end){if(await page.evaluate(fn))return;await new Promise(r=>setTimeout(r,100));}throw new Error('Timed out: '+fn.toString());};
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  page.on('dialog',dialog=>dialog.accept());
  await until(()=>!!window.app?.navBar?._el,{timeout:30000});
  assert.equal(await page.evaluate(()=>window.app.buttplugManager.connected),false);
  await page.locator('.language-prompt__btn[data-locale=en]').click({force:true});
  console.log('Window and first-run language selection ready.');
  await page.locator('[data-view-id=composer]').click({force:true});
  await until(()=>document.querySelectorAll('.fc-clip').length===4);
  await page.locator('.fc-library-filters summary').click({force:true});
  assert.equal(await page.locator('[data-field=drafts]').isChecked(),false);
  assert.ok((await page.locator('.fc-dataset-review').textContent()).includes('2 draft variants'));
  await page.locator('[data-field=drafts]').check({force:true});assert.equal(await page.locator('.fc-clip').count(),6);
  await page.locator('[data-field=search]').fill('Season/Alternate');assert.equal(await page.locator('.fc-clip').count(),1);
  assert.ok((await page.locator('.fc-clip-category').textContent()).includes('Draft, Alternate'));
  assert.ok((await page.locator('.fc-imported-categories').textContent()).includes('Season/Alternate'));
  await page.locator('.fc-clip-details [data-field=tag]').fill('My folder');await page.locator('.fc-clip-details [data-field=tag]').press('Tab');
  await until(()=>window.app.composer.catalog.clips.find(c=>c.id==='synthetic-draft').manual_categories===true);
  assert.ok((await page.locator('.fc-clip-category').textContent()).includes('My folder'));
  await page.locator('[data-action=reset-category]').click({force:true});
  await until(()=>window.app.composer.catalog.clips.find(c=>c.id==='synthetic-draft').manual_categories===false);
  assert.deepEqual(await page.evaluate(()=>window.app.composer.catalog.clips.find(c=>c.id==='synthetic-draft').categories),['Draft','Alternate']);
  assert.equal(await page.locator('[data-action=reset-category]').count(),0);
  await page.locator('[data-field=search]').fill('');
  console.log('PASS: HF folder-path search, multiple category labels, persisted manual override and restoring imported categories.');
  await page.locator('[data-field=library-view]').selectOption('audio-sync');assert.equal(await page.locator('.fc-clip').count(),1);
  assert.equal(await page.locator('.fc-clips .fc-audio-sync-badge').count(),1);
  assert.ok((await page.locator('.fc-clip-details .fc-audio-sync-note').textContent()).includes('song-generated'));
  await page.locator('[data-field=library-view]').selectOption('all');
  await page.locator('[data-field=drafts]').uncheck({force:true});assert.equal(await page.locator('.fc-clip').count(),4);
  await page.locator('[data-field=library-view]').selectOption('ready');assert.equal(await page.locator('.fc-clip').count(),2);
  await page.locator('[data-field=library-view]').selectOption('local');assert.equal(await page.locator('.fc-clip').count(),3);
  const ids=await page.evaluate(()=>Object.fromEntries(window.app.composer.catalog.clips.map(c=>[c.name,c.id])));
  const rateClip=async(id,value)=>{await page.locator(`[data-action=inspect-library-clip][data-id="${id}"]`).click({force:true});await page.locator(`[data-field=rating][data-id="${id}"]`).selectOption(value);};
  assert.equal(await page.locator('.fc-clips [data-field=rating]').count(),0,'rows contain no repeated edit forms');
  assert.equal(await page.locator('.fc-clip-details [data-field=rating]').count(),1);
  await rateClip(ids['A.mp4'],'4');
  await until(()=>window.app.composer.catalog.clips.find(c=>c.name==='A.mp4').user_rating===4);
  await rateClip(ids['B.mp4'],'5');
  await until(()=>window.app.composer.catalog.clips.find(c=>c.name==='B.mp4').user_rating===5);
  assert.equal(await page.locator('.fc-clip').first().getAttribute('data-clip-id'),ids['B.mp4']);
  await page.locator('[data-field=library-sort]').selectOption('name');assert.equal(await page.locator('.fc-clip').first().getAttribute('data-clip-id'),ids['A.mp4']);
  await page.locator('[data-field=library-sort]').selectOption('rating');
  await page.locator('[data-field=min_rating]').selectOption('4');assert.equal(await page.locator('.fc-clip').count(),2,'unrated local video excluded');
  await page.locator('[data-field=library-view]').selectOption('all');assert.equal(await page.locator('.fc-clip').count(),3,'remote variant remains discoverable');
  await page.locator('[data-field=library-view]').selectOption('ready');
  await page.locator('#composer-container [data-field=song]').selectOption(song.id);
  await page.locator('.fc-selection-bar [data-action=section-folders]').click({force:true});
  assert.equal(await page.locator('.fc-folder-dialog input[value=Alternate]').count(),1,'HF category labels appear in the song-section folder picker');
  await page.locator('.fc-folder-dialog button[value=cancel]').click({force:true});
  assert.equal(await page.evaluate(()=>window.app.composer.session.min_rating),4);
  assert.equal(await page.locator('[data-field=playback-mode]').inputValue(),'song');
  assert.ok(await page.evaluate(()=>!window.app.composer.session.analysis&&!window.app.composer.session.placements.length&&!window.app.composer.prepared));
  await page.evaluate(async()=>{
    const context=new AudioContext(),analyser=context.createAnalyser(),source=context.createMediaElementSource(window.app.composer.player.audio);
    source.connect(analyser);analyser.connect(context.destination);await context.resume();window.songAudioProbe={context,analyser};
  });
  await page.locator('[data-field=volume]').fill('0.6');await page.locator('[data-field=volume]').dispatchEvent('change');
  await page.locator('[data-action=play]').click({force:true});
  await until(()=>{
    const c=window.app.composer,samples=new Float32Array(2048);window.songAudioProbe.analyser.getFloatTimeDomainData(samples);
    return c.player.audio.currentTime>.3&&c.position>300&&samples.some(v=>Math.abs(v)>.01);
  },{timeout:10000});
  assert.ok(await page.evaluate(()=>!window.app.composer.player.audio.muted&&window.app.composer.player.audio.volume===.6&&!window.app.composer.devices.active));
  assert.equal(await page.evaluate(()=>window.app.composer.prepared),null,'listening never compiles clips or scripts');
  await page.locator('[data-action=play]').click({force:true});
  assert.equal(await page.evaluate(()=>window.app.composer.player.audio.paused),true);
  await page.locator('[data-field=seek]').fill('2200');await page.locator('[data-field=seek]').dispatchEvent('change');
  assert.ok(await page.evaluate(()=>Math.abs(window.app.composer.player.audio.currentTime-2.2)<.01&&window.app.composer.player.audio.paused));
  const wave=await page.locator('.fc-wave').boundingBox();
  await page.locator('.fc-wave').click({position:{x:wave.width/3,y:32},force:true});
  assert.ok(await page.evaluate(()=>Math.abs(window.app.composer.player.audio.currentTime-2)<.02));
  await page.locator('[data-action=play]').click({force:true});await until(()=>window.app.composer.player.audio.currentTime>2.25);
  await page.locator('[data-action=stop]').click({force:true});
  assert.ok(await page.evaluate(()=>window.app.composer.player.audio.paused&&window.app.composer.position===0&&window.app.composer.player.audio.currentTime===0));
  console.log('PASS: audible song signal before analysis or assembly, play/pause, waveform and slider seek, volume, stop, and devices off.');
  await checkTimelineEditing(page,until);
  assert.equal(await page.locator('[data-field=output-preset]').inputValue(),'portrait-1080');
  const framing=()=>{const root=document.querySelector('#composer-container'),frame=root.querySelector('.fc-preview').getBoundingClientRect(),stage=root.querySelector('.fc-preview-stage').getBoundingClientRect();return {ratio:frame.width/frame.height,inside:frame.width<=stage.width&&frame.height<=stage.height+1,fits:[...root.querySelectorAll('.fc-preview video')].map(v=>getComputedStyle(v).objectFit)};};
  let frame=await page.evaluate(framing);assert.ok(Math.abs(frame.ratio-9/16)<.005&&frame.inside);assert.deepEqual(frame.fits,['cover','cover']);
  await page.setViewportSize({width:700,height:1000});frame=await page.evaluate(framing);assert.ok(Math.abs(frame.ratio-9/16)<.005&&frame.inside,'portrait framing stays correct on narrow screens');
  await page.setViewportSize({width:1500,height:1080});
  await page.locator('[data-action=analyze]').click({force:true});
  await until(()=>!!window.app.composer.session.analysis,{timeout:20000});
  await page.locator('[data-action=assemble]').click({force:true});
  await until(()=>window.app.composer.session.placements.length>0);
  await page.locator('[data-action=prepare]').dispatchEvent('click');
  await until(()=>!!window.app.composer.prepared&&!window.app.composer.preparing,{timeout:20000});
  assert.equal(await page.locator('[data-field=playback-mode]').inputValue(),'preview');
  console.log('Song analyzed and preview prepared.');
  assert.equal(await page.evaluate(()=>window.app.composer.prepared.snapshot.scripts.L0.metadata.chapters[1].startTime),1000);
  await page.locator('[data-action=play]').click({force:true});
  await until(()=>window.app.composer.player.audio.currentTime>2.2,{timeout:15000});
  await page.locator('[data-action=play]').click({force:true});
  assert.equal(await page.evaluate(()=>window.app.composer.player.audio.paused),true);
  await page.evaluate(()=>window.app.composer.setPosition(4100));
  await until(()=>!window.app.composer.player.aligning);
  const clocks=await page.evaluate(()=>{const p=window.app.composer.player;return {audio:p.audio.currentTime,video:p.videos[p.active].currentTime,start:p.current.start_ms,paused:p.audio.paused};});
  assert.ok(Math.abs(clocks.video-(clocks.audio-clocks.start/1000))<.08);assert.ok(clocks.paused);
  await page.locator('[data-field=playback-mode]').selectOption('song');
  assert.ok(await page.evaluate(()=>!window.app.composer.prepared&&Math.abs(window.app.composer.player.audio.currentTime-4.1)<.01&&window.app.composer.player.videos.every(v=>v.paused&&v.hidden)));
  await page.locator('[data-action=play]').click({force:true});await until(()=>window.app.composer.player.audio.currentTime>4.35);
  await page.locator('[data-action=play]').click({force:true});await page.evaluate(()=>window.app.composer.setPosition(4100));
  await page.locator('[data-action=prepare]').dispatchEvent('click');await until(()=>!!window.app.composer.prepared&&!window.app.composer.preparing);
  assert.ok(await page.evaluate(()=>Math.abs(window.app.composer.player.audio.currentTime-4.1)<.01&&!window.app.composer.player.intent),'preparing preview preserves the listening position and stays paused');
  const placements=await page.evaluate(()=>JSON.stringify(window.app.composer.session.placements));
  await page.locator('[data-field=output-preset]').selectOption('landscape-720');
  assert.equal(await page.evaluate(()=>window.app.composer.prepared),null,'format changes invalidate preview');
  frame=await page.evaluate(framing);assert.ok(Math.abs(frame.ratio-16/9)<.005&&frame.inside);
  await page.locator('[data-field=output-fit]').selectOption('contain');assert.deepEqual((await page.evaluate(framing)).fits,['contain','contain']);
  await page.locator('[data-action=undo]').click({force:true});assert.equal(await page.locator('[data-field=output-fit]').inputValue(),'cover');
  await page.locator('[data-action=redo]').click({force:true});assert.equal(await page.locator('[data-field=output-fit]').inputValue(),'contain');
  await page.locator('[data-field=output-preset]').selectOption('portrait-1080');assert.equal(await page.locator('[data-field=output-fit]').inputValue(),'cover');
  assert.equal(await page.evaluate(()=>JSON.stringify(window.app.composer.session.placements)),placements,'framing edits preserve the timeline');
  await page.locator('[data-action=prepare]').dispatchEvent('click');await until(()=>!!window.app.composer.prepared&&!window.app.composer.preparing);
  await page.locator('[data-action=save]').click({force:true});await until(()=>window.app.composer.session.revision===1);
  await page.locator('[data-field=min_rating]').selectOption('5');
  assert.equal(await page.evaluate(()=>window.app.composer.prepared),null,'raising minimum invalidates preview');
  await page.locator('[data-field=library-view]').selectOption('used');assert.equal(await page.locator('.fc-clip').count(),2,'used clips below minimum stay visible');
  assert.ok(await page.locator('.fc-library > .fc-rating-warning').isVisible());
  await page.locator('[data-action=prepare]').dispatchEvent('click');await until(()=>!window.app.composer.preparing&&document.querySelector('[data-status]').textContent.includes('below the 5★ minimum'));
  assert.equal(await page.evaluate(()=>window.app.composer.prepared),null);
  const lowPlacement=await page.evaluate(()=>{const c=window.app.composer;return c.session.placements.find(p=>c.catalog.clips.find(clip=>clip.id===p.clip_id).user_rating===4).id;});
  await page.locator(`.fc-placement-strip button[data-placement="${lowPlacement}"]`).click({force:true});
  assert.equal(await page.locator('[data-field=clip_id] option:checked').getAttribute('disabled'),'');
  assert.equal(await page.locator('[data-field=clip_id] option:not(:disabled)').count(),1);
  await page.locator('[data-action=assemble]').click({force:true});
  await until(()=>window.app.composer.session.placements.every(p=>window.app.composer.catalog.clips.find(c=>c.id===p.clip_id).user_rating===5));
  assert.equal(await page.locator('.fc-clip').count(),1);assert.equal(await page.locator('.fc-library > .fc-rating-warning').isVisible(),false);
  await page.locator('[data-action=save]').click({force:true});await until(()=>window.app.composer.session.revision===2&&!window.app.composer.dirty);
  const sessionId=await page.evaluate(()=>window.app.composer.session.id);
  await page.locator('[data-field=min_rating]').selectOption('4');
  await page.locator('[data-field=output-preset]').selectOption('landscape-720');
  await page.locator('[data-field=saved]').selectOption(sessionId);await until(()=>window.app.composer.session.min_rating===5);
  assert.equal(await page.locator('[data-field=min_rating]').inputValue(),'5','saved minimum restored');
  assert.equal(await page.locator('[data-field=output-preset]').inputValue(),'portrait-1080','saved format restored');
  assert.equal(await page.locator('[data-field=output-fit]').inputValue(),'cover');
  await page.locator('[data-action=prepare]').dispatchEvent('click');await until(()=>!!window.app.composer.prepared&&!window.app.composer.preparing);
  await rateClip(ids['B.mp4'],'4');
  await until(()=>window.app.composer.catalog.clips.find(c=>c.name==='B.mp4').user_rating===4);
  assert.equal(await page.evaluate(()=>window.app.composer.prepared),null,'lowering a used rating invalidates preview');
  await rateClip(ids['B.mp4'],'5');
  await until(()=>window.app.composer.catalog.clips.find(c=>c.name==='B.mp4').user_rating===5);
  // Delay the IPC response after compilation, then change a used rating before it arrives.
  await page.evaluate(async()=>{
    const c=window.app.composer,ipc=c.ipc;let compiled;
    const ready=new Promise(resolve=>{compiled=resolve;}),gate=new Promise(resolve=>{window.releaseComposerPrepare=resolve;});
    c.ipc=async function(action,payload){const result=await ipc.call(this,action,payload);if(action==='prepare'){compiled();await gate;}return result;};
    window.pendingComposerPrepare=c.prepare().finally(()=>{c.ipc=ipc;});await ready;
  });
  await rateClip(ids['B.mp4'],'4');
  await until(()=>window.app.composer.catalog.clips.find(c=>c.name==='B.mp4').user_rating===4);
  await page.evaluate(async()=>{window.releaseComposerPrepare();await window.pendingComposerPrepare;delete window.pendingComposerPrepare;delete window.releaseComposerPrepare;});
  assert.equal(await page.evaluate(()=>window.app.composer.prepared),null,'a late IPC response cannot restore a preview after a rating edit');
  await rateClip(ids['B.mp4'],'5');
  await until(()=>window.app.composer.catalog.clips.find(c=>c.name==='B.mp4').user_rating===5);
  console.log('PASS: ready/local/used views, rating sort, 4★+/5★ assembly, stale-preview rejection, manual ratings and persisted minimum.');
  await page.locator('.fc-section-row[data-section="0"] [data-action=select-section]').click({force:true});
  await chooseSectionFolders(page);
  const untouched=await page.evaluate(()=>{const s=window.app.composer.session;return s.placements.filter(p=>p.section_id!==s.sections[0].id).map(p=>p.id);});
  await page.evaluate(()=>window.app.composer.setPosition(200));await page.locator('[data-action=mark-in]').click({force:true});
  await page.evaluate(()=>window.app.composer.setPosition(800));await page.locator('[data-action=mark-out]').click({force:true});
  await until(()=>window.app.composer.session.placements.some(p=>p.clip_id===null));
  assert.deepEqual(await page.evaluate(()=>{const c=window.app.composer;return c.session.placements.filter(p=>p.section_id===c.session.sections[0].id).map(p=>[p.start_ms,p.end_ms]);}),[[0,200],[200,800],[800,1000]]);
  assert.ok(await page.evaluate(ids=>ids.every(id=>window.app.composer.session.placements.some(p=>p.id===id)),untouched),'category and region edits preserve other sections');
  await page.locator('[data-action=save]').click({force:true});await until(()=>window.app.composer.session.revision===3&&!window.app.composer.dirty);
  await page.locator('[data-action=prepare]').dispatchEvent('click');await until(()=>!window.app.composer.preparing&&document.querySelector('[data-status]').textContent.includes('regions are empty'));
  await page.locator('[data-action=assemble]').click({force:true});await until(()=>window.app.composer.session.placements.every(p=>p.clip_id));
  const middle=await page.evaluate(()=>window.app.composer.session.placements.find(p=>p.start_ms===200&&p.end_ms===800).id);
  await page.locator(`.fc-placement-strip button[data-placement="${middle}"]`).click({force:true});
  await page.locator('[data-field=source_in_ms]').fill('0.100');await page.locator('[data-field=source_in_ms]').dispatchEvent('change');
  await page.locator('[data-field=snap-audio]').uncheck({force:true});
  await page.locator('[data-field=timeline-zoom]').selectOption('4');
  const edge=page.locator(`[data-region-edge=end][data-region-id="${middle}"]`);await edge.evaluate(el=>el.scrollIntoView({block:'center'}));
  const edgeBox=await edge.boundingBox(),trackWidth=await page.locator('.fc-placement-strip').evaluate(el=>el.getBoundingClientRect().width);
  await page.mouse.move(edgeBox.x+edgeBox.width/2,edgeBox.y+edgeBox.height/2);await page.mouse.down();await page.mouse.move(edgeBox.x+edgeBox.width/2+trackWidth*50/6000,edgeBox.y+edgeBox.height/2,{steps:5});await page.mouse.up();
  const afterRoll=await page.evaluate(()=>{const c=window.app.composer;return c.session.placements.find(p=>p.id===c.selectedPlacement);});
  assert.ok(Math.abs(afterRoll.end_ms-850)<=2);assert.equal(afterRoll.start_ms,200);
  assert.ok(await page.evaluate(()=>{const ps=window.app.composer.session.placements;return ps.every((p,i)=>!i||p.start_ms===ps[i-1].end_ms);}));
  await page.locator('[data-action=undo]').click({force:true});assert.equal(await page.evaluate(()=>window.app.composer.session.placements.find(p=>p.start_ms===200).end_ms),800);
  await page.locator('[data-action=redo]').click({force:true});
  const source=page.locator('[data-source-drag]');await source.evaluate(el=>el.scrollIntoView({block:'center'}));
  const sourceBox=await source.boundingBox(),sourceWidth=await page.locator('.fc-source-rail').evaluate(el=>el.getBoundingClientRect().width);
  await page.mouse.move(sourceBox.x+sourceBox.width/2,sourceBox.y+sourceBox.height/2);await page.mouse.down();await page.mouse.move(sourceBox.x+sourceBox.width/2+sourceWidth*.2,sourceBox.y+sourceBox.height/2,{steps:5});await page.mouse.up();
  const trimmed=await page.evaluate(()=>{const c=window.app.composer;return c.session.placements.find(p=>p.id===c.selectedPlacement);});
  assert.ok(Math.abs(trimmed.source_in_ms-500)<=2);assert.equal(trimmed.end_ms,afterRoll.end_ms);assert.equal(trimmed.locked,true);
  await page.locator('[data-action=variation]').click({force:true});
  assert.deepEqual(await page.evaluate(id=>window.app.composer.session.placements.find(p=>p.id===id),middle),trimmed);
  await page.locator('.fc-section-row[data-section="1"] [data-action=select-section]').click({force:true});await page.locator('[data-action=merge]').click({force:true});
  await until(()=>window.app.composer.session.sections.length===5);
  await page.locator('[data-field=region-beats]').selectOption('2');await page.locator('[data-action=suggest-regions]').click({force:true});
  await until(()=>document.querySelectorAll('.fc-audio-markers span').length>0);
  await page.locator('[data-action=apply-regions]').click({force:true});await page.locator('[data-action=assemble]').click({force:true});
  await until(()=>window.app.composer.session.placements.every(p=>p.clip_id));
  assert.deepEqual(await page.evaluate(id=>window.app.composer.session.placements.find(p=>p.id===id),middle),trimmed);
  await page.locator('[data-action=save]').click({force:true});await until(()=>window.app.composer.session.revision===4&&!window.app.composer.dirty);
  await page.locator('[data-field=saved]').selectOption(sessionId);await until(()=>window.app.composer.session.revision===4&&!window.app.composer.dirty);
  assert.deepEqual(await page.evaluate(id=>window.app.composer.session.placements.find(p=>p.id===id),middle),trimmed);
  await page.locator(`.fc-placement-strip button[data-placement="${middle}"]`).click({force:true});
  await page.locator('[data-field=timeline-zoom]').selectOption('1');
  await page.locator('.fc-timeline-viewport').evaluate(el=>el.scrollLeft=0);
  console.log('PASS: category pools, marked empty regions, drag cuts, drag source trim, undo/redo, kept trims, audio-cut suggestions, section merge and recipe restoration.');
  await page.locator('[data-action=inspector-section]').click({force:true});
  await page.locator('[data-field=motion]').selectOption('song');
  await page.locator('[data-action=prepare]').dispatchEvent('click');await until(()=>!!window.app.composer.prepared&&!window.app.composer.preparing);
  assert.ok(await page.evaluate(()=>window.app.composer.prepared.snapshot.blocks.some(b=>b.kind==='song')));
  await page.locator('[data-action=render]').click({force:true});await until(()=>!!window.app.composer.rendered,{timeout:45000});
  const rendered=await page.evaluate(()=>window.app.composer.rendered);const info=await service.probe(rendered.path,signal);
  assert.equal(info.width,1080);assert.equal(info.height,1920);assert.equal(rendered.output.fit,'cover');
  console.log('PASS: portrait/landscape preview geometry, fill/fit modes, undo/redo, saved format, mixed source playback and real 1080×1920 export.');
  await page.locator('[data-action=inspector-clip]').click({force:true});
  await page.setViewportSize({width:1500,height:1600});
  await page.evaluate(()=>document.getElementById('composer-container').scrollTop=0);
  await page.locator('.fc-library-filters').evaluate(el=>el.open=false);
  await page.screenshot({path:path.join(checkout,'docs','composer-implemented.png'),fullPage:true});
  await page.locator('[data-action=open-render]').click({force:true});
  await until(()=>window.app._currentView()==='player'&&window.app.funscriptEngine.isLoaded&&window.app.buttplugSync._axisActions.size===5);
  await until(()=>window.app.videoPlayer.video.videoWidth===1080&&window.app.videoPlayer.video.videoHeight===1920);
  assert.equal(await page.evaluate(()=>window.app.videoPlayer.paused),true);
  assert.equal(await page.evaluate(()=>window.app.tcodeSync._axisActions.size),5);
  const backend=await page.evaluate(async()=>{const before=await window.funsync.getBackendPort(),result=await window.funsync.restartBackend();return {before,after:await window.funsync.getBackendPort(),result};});
  assert.ok(backend.result.success);assert.equal(backend.before,backend.after);
  await page.locator('#btn-player-back').click({force:true});
  await until(()=>window.app._currentView()==='composer'&&window.app.composer.visible);
  await page.locator('.fc-library-filters').evaluate(el=>el.open=true);
  await page.locator('[data-field=drafts]').check({force:true});
  await page.locator('#composer-container [data-field=song]').selectOption(song.id);
  assert.equal(await page.evaluate(()=>window.app.composer.session.include_drafts),true,'explicit choice carries into a new song');
  await page.locator('[data-field=min_rating]').selectOption('5');
  await page.locator('[data-field=library-view]').selectOption('all');
  assert.equal(await page.locator('[data-clip-id=synthetic-draft]').count(),1);
  assert.equal(await page.locator('[data-clip-id=synthetic-unrated-draft]').count(),0,'draft inclusion does not bypass stars');
  await page.locator('[data-field=min_rating]').selectOption('0');
  assert.equal(await page.locator('[data-clip-id=synthetic-unrated-draft]').count(),1);
  await page.locator('[data-field=min_rating]').selectOption('5');
  // Restrict this fixture to draft clips; category checkbox interaction is covered above.
  await page.evaluate(()=>window.app.composer.edit(s=>s.sections.forEach(section=>{section.categories=['Draft'];})));
  await page.locator('[data-action=assemble]').click({force:true});
  await until(()=>window.app.composer.session.placements.length===6&&window.app.composer.session.placements.every(p=>p.clip_id==='synthetic-draft'));
  await page.locator('[data-action=prepare]').dispatchEvent('click');
  await until(()=>!window.app.composer.preparing&&document.querySelector('[data-status]').textContent.includes('Analyze the song'));
  await page.locator('[data-action=analyze]').click({force:true});await until(()=>!!window.app.composer.session.analysis);
  await page.locator('[data-action=save]').click({force:true});await until(()=>window.app.composer.session.revision===1&&!window.app.composer.dirty);
  const draftSessionId=await page.evaluate(()=>window.app.composer.session.id),draftPlacements=await page.evaluate(()=>JSON.stringify(window.app.composer.session.placements));
  await page.locator('[data-action=prepare]').dispatchEvent('click');await until(()=>!!window.app.composer.prepared&&!window.app.composer.preparing);
  assert.ok(await page.evaluate(()=>window.app.composer.prepared.snapshot.blocks.every(b=>b.kind==='song'&&b.audio_sync)));
  await page.locator('.fc-placement-strip button[data-placement]').first().click({force:true});
  assert.ok((await page.locator('.fc-region-inspector .fc-audio-sync-note').textContent()).includes('song-generated'));
  await page.evaluate(async()=>{
    const c=window.app.composer,ipc=c.ipc;
    c.ipc=async function(action,payload){const result=await ipc.call(this,action,payload);if(action==='state')result.clips.find(clip=>clip.id==='synthetic-draft').audio_sync=false;return result;};
    try{await c.refresh();}finally{c.ipc=ipc;}
  });
  assert.equal(await page.evaluate(()=>window.app.composer.prepared),null,'changing a used audio-sync label invalidates its prepared motion');
  await page.evaluate(()=>window.app.composer.refresh());
  console.log('PASS: audio-sync badges/filter, analysis requirement, per-region song motion and invalidation after label changes.');
  await page.locator('[data-field=drafts]').uncheck({force:true});
  assert.equal(await page.evaluate(()=>window.app.composer.prepared),null);
  assert.equal(await page.evaluate(()=>JSON.stringify(window.app.composer.session.placements)),draftPlacements,'disabling drafts preserves the editable timeline');
  assert.equal(await page.locator('[data-clip-id=synthetic-draft]').count(),0);
  await page.locator('[data-field=library-view]').selectOption('used');
  assert.equal(await page.locator('[data-clip-id=synthetic-draft]').count(),1,'excluded used drafts remain visible');
  assert.ok(await page.locator('.fc-library > .fc-draft-warning').isVisible());
  await page.locator('.fc-placement-strip button[data-placement]').first().click({force:true});
  assert.equal(await page.locator('[data-field=clip_id] option:checked').getAttribute('disabled'),'');
  assert.equal(await page.locator('[data-field=clip_id] option:not(:disabled)').count(),0);
  await page.locator('[data-action=prepare]').dispatchEvent('click');await until(()=>!window.app.composer.preparing&&document.querySelector('[data-status]').textContent.includes('draft scripts are disabled'));
  await page.locator('[data-action=undo]').click({force:true});assert.equal(await page.locator('[data-field=drafts]').isChecked(),true);
  await page.locator('[data-action=redo]').click({force:true});assert.equal(await page.locator('[data-field=drafts]').isChecked(),false);
  await page.locator('[data-field=saved]').selectOption(draftSessionId);await until(()=>window.app.composer.session.include_drafts&&!window.app.composer.dirty);
  assert.equal(await page.locator('[data-field=drafts]').isChecked(),true,'saved draft choice is restored');
  await page.evaluate(async()=>{
    const c=window.app.composer,ipc=c.ipc;let compiled;
    const ready=new Promise(resolve=>{compiled=resolve;}),gate=new Promise(resolve=>{window.releaseDraftPrepare=resolve;});
    c.ipc=async function(action,payload){const result=await ipc.call(this,action,payload);if(action==='prepare'){compiled();await gate;}return result;};
    window.pendingDraftPrepare=c.prepare().finally(()=>{c.ipc=ipc;});await ready;
  });
  await page.locator('[data-field=drafts]').uncheck({force:true});
  await page.evaluate(async()=>{window.releaseDraftPrepare();await window.pendingDraftPrepare;});
  assert.equal(await page.evaluate(()=>window.app.composer.prepared),null,'late preparation cannot restore excluded draft motion');
  await page.locator('[data-field=playback-mode]').selectOption('song');
  await page.locator('[data-action=play]').click({force:true});await until(()=>window.app.composer.player.audio.currentTime>.2);
  assert.ok(await page.evaluate(()=>!window.app.composer.prepared&&!window.app.composer.devices.active),'excluded drafts do not prevent song-only listening');
  await page.locator('[data-action=stop]').click({force:true});
  console.log('PASS: draft opt-in, independent stars, assembly, manual choices, preview rejection, saved choice, undo/redo, and late preparation invalidation.');
  await checkLargeLibrary(page);
  await page.evaluate(()=>document.getElementById('composer-container').scrollTop=0);
  const libraryBounds=await page.locator('.fc-library').boundingBox();
  await page.screenshot({path:path.join(checkout,'docs','composer-library.png'),clip:libraryBounds});
  assert.deepEqual(errors,[]);
  console.log('PASS: actual Electron launch, song analysis, assembly, clip switching, pause/seek, recipe save, song motion, FFmpeg export, and six-axis FunSync playback handoff.');
}catch(error){console.error(error.message);if(app){for(const page of app.windows())if(page.url().includes('index.html')){console.error(await page.evaluate(()=>({ready:document.readyState,nav:!!window.app?.navBar,navElement:!!window.app?.navBar?._el,status:document.querySelector('[data-status]')?.textContent,view:window.app?._currentView(),body:document.body.innerText.slice(0,1500)})));await page.screenshot({path:path.join(root,'failure.png')}).catch(()=>{});}}throw error;}
finally{if(app){for(const page of app.windows())if(page.url().includes('index.html'))await page.evaluate(()=>{if(window.app?.composer)window.app.composer.dirty=false;}).catch(()=>{});app.process().kill('SIGTERM');await app.close().catch(()=>{});}await fs.rm(root,{recursive:true,force:true});}
