import {MangaPlayer} from './player.js';
import {MangaTransitions} from './transitions.js';
import {MangaBubbles} from './bubbles.js';
import {ComposerDeviceSession} from '../composer/device-session.js';
import {DEFAULT_PRESENTATION,presentation} from '../../packages/manga-core/motion.mjs';
import {selectedTake,nextReadingPage} from '../../packages/manga-core/sequence.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=ms=>`${Math.floor(Math.max(0,ms)/60000)}:${(Math.max(0,ms)/1000%60).toFixed(1).padStart(4,'0')}`;
const options=(pairs,value)=>pairs.map(([id,label])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(label)}</option>`).join('');
export class MangaView {
  constructor(app,root){
    this.app=app;this.root=root;this.visible=false;this.settings={...DEFAULT_PRESENTATION};this.overrides={};this.pageIndex=0;this.zoom=1;this.generation=0;this.devices=new ComposerDeviceSession(app,{owner:'manga'});this.bookmarks=[];
    root.className='mg';root.innerHTML=`
      <header class="mg-header"><div><small>ANIMATED MANGA</small><h1>Open a book</h1></div><div class="mg-actions"><button data-action="open">Open H3 project…</button><button data-action="open-package">Open package…</button><select data-field="recent" aria-label="Recent manga"><option value="">Recent books…</option></select><button data-action="refresh">Refresh</button><button data-action="export">Export book…</button><button data-action="details">Settings &amp; details</button></div></header>
      <div class="mg-status" role="status"><span>Read original pages, then click a panel to animate it.</span><progress hidden></progress><button data-action="cancel" hidden>Cancel</button></div>
      <div class="mg-layout"><aside class="mg-pages" aria-label="Pages"></aside><main class="mg-reader">
        <div class="mg-page-tools"><button data-action="previous-page" aria-label="Previous page">← Page</button><label>Page <input data-field="page" type="number" min="1" value="1"></label><span class="mg-page-count"></span><button data-action="next-page" aria-label="Next page">Page →</button><button data-action="bookmark">☆ Bookmark</button><select data-field="layout" aria-label="Reading layout"><option value="page">Single page</option><option value="scroll">Scroll pages</option></select><button data-action="zoom-out" aria-label="Zoom out">−</button><button data-action="fit">Fit page</button><button data-action="zoom-in" aria-label="Zoom in">+</button><label><input data-field="bubbles" type="checkbox" checked>Bubbles</label><label title="Show all enabled bubble layers throughout the animation, without timed entrances or exits."><input data-setting="ignoreBubbleTiming" type="checkbox">Ignore bubble timing</label><button data-action="fullscreen">Fullscreen</button></div>
        <div class="mg-surface"><div class="mg-paper-area"><div class="mg-empty">Your manga stays a manga.<p>Open an H3 Animator project or a portable .fcmanga book.</p></div></div>
          <div class="mg-focus" hidden><div class="mg-focus-header"><button data-action="back">← Back to page</button><span class="mg-panel-title"></span><button data-action="inline">Animate in page</button></div><div class="mg-stage"><video playsinline preload="auto" hidden></video><video playsinline preload="auto" hidden></video><img class="mg-still" alt="Panel artwork" hidden><canvas class="mg-bubbles" aria-label="Timed speech bubbles" hidden></canvas></div></div>
        </div>
        <div class="mg-transport"><div class="mg-transport-row"><button class="mg-inline-exit" data-action="back">Back to page</button><button data-action="previous-panel">Previous panel</button><button data-action="play" class="mg-primary">▶ Play</button><button data-action="next-panel">Next panel</button><button data-action="stop">Stop</button><span class="mg-time">0:00.0</span><input data-field="seek" type="range" min="0" max="1" step="1" value="0" aria-label="Panel playback position"><label>Volume <input data-field="volume" type="range" min="0" max="1" step="0.01" value="0.8"></label></div>
        <div class="mg-transport-row"><label>Autoplay <select data-setting="autoplay"><option value="page">This page</option><option value="continuous">Across pages</option><option value="manual">Manual</option></select></label><label>While reading <select data-setting="mode"><option value="none">Continue normally</option><option value="pause">Pause to read</option><option value="loop">Loop panel</option><option value="extend">Extend motion</option></select></label><span class="mg-play-state">Select a panel</span><span class="mg-spacer"></span><span class="mg-device-state">Devices off</span><button data-action="connect">Devices</button><button data-action="prepare">Prepare device sync</button></div></div>
      </main><aside class="mg-details" hidden></aside></div>`;
    this.transitions=new MangaTransitions(root);
    this.bubbleDisplay=new MangaBubbles(root.querySelector('.mg-bubbles'));
    this.player=new MangaPlayer([...root.querySelectorAll('video')],{onChange:s=>this.tick(s),onError:e=>this.message(e,true),onEnd:options=>void this.runEnd(options).catch(e=>this.message(e.message,true)),onTransition:phase=>{if(phase==='begin')this.transitions.begin();else if(phase==='ready')this.transitions.ready();else this.transitions.cancel();}});
    root.addEventListener('click',e=>{if(this.suppressClick){this.suppressClick=false;return;}const panel=e.target.closest('[data-panel]');if(panel){void this.focusPanel(panel.dataset.panel,Number(panel.dataset.page)).catch(e=>this.message(e.message,true));return;}const button=e.target.closest('[data-action]');if(button)void this.action(button.dataset.action,button).catch(e=>this.message(e.message,true));});
    root.addEventListener('change',e=>void this.change(e.target).catch(e=>this.message(e.message,true)));
    root.querySelector('[data-field=seek]').addEventListener('input',e=>{this.root.querySelector('.mg-time').textContent=time(Number(e.target.value));});
    root.querySelector('[data-field=volume]').addEventListener('input',e=>{this.settings.volume=Number(e.target.value);this.player.setVolume(this.settings.volume);});
    document.addEventListener('keydown',e=>{if(this.visible&&e.key==='Escape'&&!this.root.querySelector('.mg-details').hidden){e.preventDefault();this.root.querySelector('.mg-details').hidden=true;return;}if(!this.visible||e.repeat||e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,select,textarea,[contenteditable=true]'))return;const action=({' ':'play',ArrowRight:this.book?.direction==='rtl'?'previous-panel':'next-panel',ArrowLeft:this.book?.direction==='rtl'?'next-panel':'previous-panel',f:'fullscreen',Escape:'back',b:'bubbles'})[e.key];if(action){e.preventDefault();void this.action(action).catch(e=>this.message(e.message,true));}},true);
    const surface=root.querySelector('.mg-surface');surface.addEventListener('pointerdown',e=>{if(e.button!==1&&(e.button!==0||this.zoom<=1))return;this.pan={x:e.clientX,y:e.clientY,left:surface.scrollLeft,top:surface.scrollTop,id:e.pointerId};});surface.addEventListener('pointermove',e=>{if(!this.pan)return;const dx=e.clientX-this.pan.x,dy=e.clientY-this.pan.y;if(Math.hypot(dx,dy)>5){surface.setPointerCapture(e.pointerId);this.suppressClick=true;surface.scrollLeft=this.pan.left-dx;surface.scrollTop=this.pan.top-dy;}});surface.addEventListener('pointerup',()=>{this.pan=null;});surface.addEventListener('pointercancel',()=>{this.pan=null;});
    this.statusTimer=setInterval(()=>{if(this.visible&&!this.player.intent)this.tick({segment:this.player.segment,position:this.player.position,playing:false,running:false,holding:this.player.holding});},1000);
    this.refreshTimer=setInterval(()=>{if(this.visible&&this.book?.kind==='h3'&&!this.busy&&!this.checking){this.checking=true;void this.ipc('changed',{id:this.book.id}).then(changed=>{if(changed)this.message('New H3 media, joined-panel sequence, bubble timing or scripts are available. Refresh when ready; this prepared page stays unchanged.');}).catch(()=>{}).finally(()=>this.checking=false);}},60000);
    this.resize=new ResizeObserver(()=>this.fitGeometry());this.resize.observe(root.querySelector('.mg-surface'));
  }
  ipc(action,payload={}){return window.funsync.manga(action,payload);}
  message(text,error=false){const el=this.root.querySelector('.mg-status');el.classList.toggle('mg-error',error);el.querySelector('span').textContent=text;}
  async show(){this.visible=true;await this.recents();if(this.book)this.fitGeometry();}
  hide(){this.cancelTurn();this.cancelPrecache();this.visible=false;this.generation++;this.player.pause();this.devices.release();this.save();if(document.fullscreenElement===this.root)void document.exitFullscreen();}
  async recents(){const list=await this.ipc('list');this.root.querySelector('[data-field=recent]').innerHTML='<option value="">Recent books…</option>'+options(list.map(b=>[b.key,`${b.title} · ${b.kind==='h3'?'H3 project':'Package'}`]),'');}
  async job(action,payload){if(this.busy)throw new Error('Wait for the current operation or cancel it.');this.busy=true;
    try{const job=await this.ipc(action,payload);if(!job)return;this.jobId=job.id;this.root.querySelector('progress').hidden=false;this.root.querySelector('[data-action=cancel]').hidden=false;
      while(true){const j=await this.ipc('job',{id:job.id});this.message(j.message||'Working…');this.root.querySelector('progress').value=j.progress;
        if(j.state==='done')return j.result;if(j.state!=='running')throw new Error(j.error||'Cancelled.');await new Promise(r=>setTimeout(r,150));}
    }finally{this.busy=false;this.jobId=null;this.root.querySelector('progress').hidden=true;this.root.querySelector('[data-action=cancel]').hidden=true;}}
  async accept(book,{persistCurrent=true}={}){if(!book)return;this.cancelTurn();this.cancelPrecache();if(persistCurrent)await this.save();this.devices.release();this.player.pause();this.generation++;this.book=book;this.player.run=null;this.run=null;this.panelId=null;this.settings=presentation({...DEFAULT_PRESENTATION,...book.presentation,...book.reader.settings});this.overrides=book.reader.overrides||book.overrides||{};this.bookmarks=book.reader.bookmarks||[];for(const page of book.pages)page.panels=page.panels.map((p,i)=>({p,order:this.overrides[p.id]?.order??i})).sort((a,b)=>a.order-b.order).map(v=>v.p);
    this.pageIndex=Math.max(0,book.pages.findIndex(p=>p.id===book.reader.pageId));this.zoom=book.reader.zoom||1;this.returnScroll=book.reader.scroll||{top:0,left:0};this.root.querySelector('[data-field=layout]').value=book.reader.layout||'page';this.root.querySelector('h1').textContent=book.title;this.root.querySelector('.mg-focus').hidden=true;this.root.querySelector('.mg-paper-area').hidden=false;
    this.player.bubbles=this.settings.bubbles;this.player.setVolume(this.settings.volume);this.renderPage();this.root.querySelector('.mg-surface').scrollTo(this.returnScroll);this.renderDetails();this.renderSettings();await this.recents();
    const panels=book.pages.flatMap(p=>p.panels),animated=panels.filter(p=>p.takes.length).length,scripts=panels.filter(p=>p.takes.find(t=>t.id===p.selected)?.scripts.L0).length;
    if(book.reader.focused!==false&&book.reader.panelId&&book.pages[this.pageIndex]?.panels.some(p=>p.id===book.reader.panelId)){await this.focusPanel(book.reader.panelId,this.pageIndex,false);const index=this.run.segments.findIndex(s=>s.panelId===book.reader.panelId&&s.iteration===(book.reader.segmentIteration||0));if(index>=0)await this.player.select(index,book.reader.localMs||0,false);}
    if(!book.pages[this.pageIndex]?.panels.length&&book.reader.panelId===`page:${book.pages[this.pageIndex]?.id}`){await this.startPage(false);if(this.run)await this.player.seekPanel(book.reader.localMs||0);}
    this.message(`${book.pages.length} pages · ${animated} animated panels · ${scripts} with motion${book.issues.length?` · ${book.issues.length} asset issues (Details)`:''}`);
  }
  asset(id){return id?this.book?.assets[id]?.url||`manga-media://asset/${id}`:'';}
  panel(){return this.book?.pages[this.pageIndex]?.panels.find(p=>p.id===this.panelId);}
  settingsFor(panel=this.panel()){return {...this.settings,...this.overrides[panel?.id]};}
  take(panel=this.panel()){return selectedTake(panel,this.overrides[panel?.id]);}
  async save(){if(!this.book)return;return this.ipc('save-reader',{id:this.book.id,reader:{focused:!this.root.querySelector('.mg-focus').hidden,pageId:this.book.pages[this.pageIndex]?.id,panelId:this.panelId,localMs:this.player.segment?this.player.position-this.player.segment.start:0,segmentIteration:this.player.segment?.iteration||0,settings:this.settings,overrides:this.overrides,bookmarks:this.bookmarks,zoom:this.zoom,layout:this.root.querySelector('[data-field=layout]').value,scroll:!this.root.querySelector('.mg-focus').hidden&&!this.root.classList.contains('mg-inline')?this.returnScroll:{top:this.root.querySelector('.mg-surface').scrollTop,left:this.root.querySelector('.mg-surface').scrollLeft}}});}
  renderSettings(){for(const el of this.root.querySelectorAll('[data-setting]')){const value=this.settings[el.dataset.setting];if(el.type==='checkbox')el.checked=!!value;else el.value=value;}this.root.querySelector('[data-field=bubbles]').checked=this.settings.bubbles;this.root.querySelector('[data-field=volume]').value=this.settings.volume;}
  renderPage(){if(!this.book)return;const focus=this.root.querySelector('.mg-focus');if(focus?.parentElement!==this.root.querySelector('.mg-surface'))this.root.querySelector('.mg-surface').append(focus);this.root.classList.remove('mg-inline');const page=this.book.pages[this.pageIndex];this.root.querySelector('[data-field=page]').value=this.pageIndex+1;this.root.querySelector('[data-field=page]').max=this.book.pages.length;this.root.querySelector('.mg-page-count').textContent=`/ ${this.book.pages.length}`;
    const thumbs=this.root.querySelector('.mg-pages'),start=Math.max(0,this.pageIndex-8);thumbs.innerHTML=`<button data-action="thumbnail-back">↑ Earlier pages</button>`+this.book.pages.slice(start,start+18).map((p,i)=>`<button data-action="page" data-index="${i+start}" class="${i+start===this.pageIndex?'mg-selected':''}"><img loading="lazy" src="${esc(this.asset(p.image))}" alt=""><span>${esc(p.label)} ${this.bookmarks.includes(p.id)?'★':''}</span><small>${p.panels.filter(p=>p.takes.length).length||'No'} animations</small></button>`).join('')+'<button data-action="thumbnail-next">Later pages ↓</button>';
    const scroll=this.root.querySelector('[data-field=layout]').value==='scroll';const pages=scroll?this.book.pages:[page];
    this.root.querySelector('.mg-paper-area').innerHTML=pages.map(p=>{
      const pi=this.book.pages.indexOf(p);return `<div class="mg-paper" data-page-index="${pi}" style="aspect-ratio:${Number(p.width)||1500}/${Number(p.height)||2122};--page-ratio:${(p.width||1500)/(p.height||2122)}"><img loading="lazy" class="mg-page-image" src="${esc(this.asset(p.image))}" alt="${esc(p.label)}">${p.panels.map((panel,i)=>{
        const [x,y,r,b]=panel.bbox;const polygon=panel.polygon?.map(pt=>`${(pt[0]-x)/(r-x)*100}% ${(pt[1]-y)/(b-y)*100}%`).join(',');return `<button class="mg-hotspot" data-panel="${esc(panel.id)}" data-page="${pi}" aria-label="${panel.takes.length?'Play':'Read'} ${panel.joined?'joined panels':'panel'} ${i+1}" title="${esc(panel.joined?.label||'')}" style="left:${x*100}%;top:${y*100}%;width:${(r-x)*100}%;height:${(b-y)*100}%;${polygon?`clip-path:polygon(${polygon})`:''}">${!this.settings.bubbles&&panel.clean?`<img src="${esc(this.asset(panel.clean))}" alt="Clean panel">`:''}<span>${panel.takes.length?'▶':'◇'} ${i+1}${panel.joined?' · Joined':''}</span></button>`;
      }).join('')}</div>`;
    }).join('');this.fitGeometry();this.root.querySelector('[data-action=bookmark]').textContent=this.bookmarks.includes(page.id)?'★ Bookmarked':'☆ Bookmark';this.prefetchNext();
  }
  fitGeometry(){const surface=this.root.querySelector('.mg-surface');if(!surface.clientHeight)return;for(const p of this.root.querySelectorAll('.mg-paper')){const ratio=Number(p.style.getPropertyValue('--page-ratio'));p.style.width=`${Math.max(150,Math.min(surface.clientWidth-32,(surface.clientHeight-24)*ratio)*this.zoom)}px`;}}
  renderDetails(){const panel=this.panel(),take=this.take(),own=this.overrides[panel?.id]||{},details=this.root.querySelector('.mg-details');details.innerHTML=`<button data-action="details" class="mg-close-details">Close settings ×</button><h2>Reading preferences</h2><label>Still reading time (seconds)<input data-setting="stillSeconds" type="number" min="0" max="600" step="1" value="${this.settings.stillSeconds}"></label><p>For each still panel, or a whole page without panels. 0 waits for Next. Choose Across pages to continue automatically between pages.</p><label>Extra reading time (seconds)<input data-setting="extraSeconds" type="number" min="1" max="600" value="${this.settings.extraSeconds}"></label><label>At the end of extra time<select data-setting="advance">${options([['manual','Wait for Next'],['budget','Advance automatically']],this.settings.advance)}</select></label><label class="mg-check"><input data-setting="readBefore" type="checkbox" ${this.settings.readBefore?'checked':''}>Read before playing</label><label class="mg-check"><input data-setting="repeatAudio" type="checkbox" ${this.settings.repeatAudio?'checked':''}>Play audio on every loop</label><label class="mg-check"><input data-setting="edgeFades" type="checkbox" ${this.settings.edgeFades?'checked':''}>Short audio fades at panel boundaries</label><p>Motion extension keeps the current panel visible and repeats a phrase from its script. Extra time is prepared in complete phrases.</p>
      ${panel?`<h2>Selected panel</h2>${panel.joined?`<p>Joined panels · ${esc(panel.joined.label)}</p>${!take?'<p>No completed video matches this active join. Generate its video in H3 or choose a different saved pair there, then Refresh.</p>':''}`:''}<p>${take?(take.scripts.L0?'Animation + motion':'Animation · no motion script'):'Still panel'}</p><label>Take<select data-panel-field="take">${options(panel.takes.map(t=>[t.id,`${t.id} · ${time(t.durationMs)}${t.scripts.L0?' · motion':''}`]),take?.id)}</select></label><label>While reading<select data-panel-field="mode">${options([['','Use book setting'],['none','Continue normally'],['pause','Pause to read'],['loop','Loop panel'],['extend','Extend motion']],own.mode||'')}</select></label>${!take?`<label>Still reading time (seconds)<input data-panel-field="stillSeconds" type="number" min="0" max="600" step="1" value="${own.stillSeconds??''}" placeholder="Book: ${this.settings.stillSeconds}"></label>`:''}<label>Panel volume gain<input data-panel-field="gain" type="number" min="0" max="2" step="0.05" value="${own.gain??1}"></label><label>Motion phrase start (seconds)<input data-panel-field="phrase-start" type="number" min="0" step="0.01" value="${own.phraseRange?own.phraseRange[0]/1000:''}" placeholder="Automatic"></label><label>Motion phrase end (seconds)<input data-panel-field="phrase-end" type="number" min="0" step="0.01" value="${own.phraseRange?own.phraseRange[1]/1000:''}" placeholder="Automatic"></label><button data-action="phrase">Apply phrase range</button><button data-action="reset-panel">Reset panel overrides</button><button data-action="order-earlier">Read earlier</button><button data-action="order-later">Read later</button><button data-action="analyze-audio">Suggest audio level</button><div class="mg-audio-suggestion"></div><p>${take?.bubbleLayers!==undefined?`Animator bubble timing · ${take.bubbleLayers.length} active layers. Refresh after editing timing in Animator.`:take?.overlay?'Bubbles toggle without restarting the video.':take?.clean&&take?.baked?'Separate bubble variants available.':'Bubble visibility depends on the available artwork.'}</p>`:''}
      <h2>Book</h2><p>${esc(this.book?.kind==='package'?'Portable reader edition':'Linked H3 project')} · originals remain unchanged.</p><label class="mg-check"><input data-field="export-alternates" type="checkbox">Include alternative takes in export</label><button data-action="clean-cache">Clear unused playback cache</button><button data-action="export-update">Export small update…</button>${this.book?.kind==='package'?'<button data-action="apply-update">Apply update…</button><button data-action="rollback-update">Roll back last update</button>':''}<label class="mg-check"><input data-field="export-encodes" type="checkbox">Keep both original video encodes</label><h3>Bookmarks</h3>${this.bookmarks.map(id=>{const index=this.book.pages.findIndex(p=>p.id===id);return `<button data-action="page" data-index="${index}">${esc(this.book.pages[index]?.label||id)}</button>`;}).join('')||'<p>No bookmarks yet.</p>'}<h3>Asset issues</h3><ul>${this.book?.issues.map(v=>`<li>${esc(v)}</li>`).join('')||'<li>No broken linked assets found.</li>'}</ul>`;}
  invalidate(){this.cancelTurn();this.cancelPrecache();this.run=null;this.devices.release();this.player.pause();this.generation++;this.message('Reading settings changed. Play to rebuild; prepare device sync again if needed.');}
  cancelTurn(){this.turningPage=null;this.transitions.cancel();}
  cancelPrecache(){this.ahead=null;this.player.clearAhead();void this.ipc('cancel-precache').catch(()=>{});}
  prefetchNext(){
    if(!this.visible||!this.book||this.ahead?.page===this.pageIndex&&!this.run)return;
    const page=nextReadingPage(this.book.pages,this.pageIndex),{volume,bubbles,ignoreBubbleTiming,...settings}=this.settings;if(page<0)return;
    const key=JSON.stringify([this.book.id,this.book.revision,page,settings,this.overrides]);
    if(this.ahead?.key===key)return;
    const ahead={key,page};this.ahead=ahead;
    void this.player.warmImage(this.asset(this.book.pages[page].image));
    ahead.promise=this.ipc('precache',{id:this.book.id,page,settings:this.settings,overrides:this.overrides}).then(run=>{
      if(this.ahead!==ahead||!this.visible)return;
      ahead.run=run;this.player.setAheadRun(run);return run;
    }).catch(()=>{if(this.ahead===ahead)ahead.failed=true;});
  }
  async ensureRun(){if(this.run)return this.run;if(!this.book)return null;const gen=this.generation;this.message('Preparing this page…');const run=await this.ipc('prepare',{id:this.book.id,page:this.pageIndex,settings:this.settings,overrides:this.overrides});if(gen!==this.generation)return null;this.run=run;if(this.ahead?.page===this.pageIndex){this.ahead=null;this.player.aheadRun=null;}this.prefetchNext();this.message(run.warnings?.length?`Page ready · ${run.warnings.join('; ')}`:'Page ready.',!!run.warnings?.length);return run;}
  async focusPanel(id,pageIndex=this.pageIndex,play=true){if(!this.book)return;const surface=this.root.querySelector('.mg-surface'),scroll={top:surface.scrollTop,left:surface.scrollLeft};if(pageIndex!==this.pageIndex){await this.page(pageIndex);}
    const gen=++this.generation;this.returnScroll=scroll;this.panelId=id;const run=await this.ensureRun();if(!run||gen!==this.generation)return;const panel=this.panel(),take=this.take();this.transitions.begin();this.root.querySelector('.mg-focus').hidden=false;this.root.querySelector('.mg-paper-area').hidden=true;this.root.classList.remove('mg-inline');
    this.root.querySelector('.mg-panel-title').textContent=panel?.joined?`${this.book.pages[this.pageIndex].label} · Joined panels · ${panel.joined.label}`:`${this.book.pages[this.pageIndex].label} · Panel ${this.book.pages[this.pageIndex].panels.indexOf(panel)+1}`;
    this.root.querySelector('.mg-stage').style.aspectRatio=`${take?.width||1500}/${take?.height||500}`;
    await this.player.load(run,id);if(gen!==this.generation||!this.visible)return;this.player.setVolume(this.settings.volume);this.renderDetails();if(play&&(!take||!this.settingsFor().readBefore))await this.player.play();}
  async startPage(play=true){
    const page=this.book?.pages[this.pageIndex];if(!page)return;
    if(page.joinedOnly){const next=nextReadingPage(this.book.pages,this.pageIndex);if(next<0){this.message('This page is already included in a joined clip. Book finished.');return;}await this.page(next,{guided:true});return this.startPage(play);}
    if(page.panels.length)return this.focusPanel(page.panels[0].id,this.pageIndex,play);
    const gen=++this.generation,run=await this.ensureRun();if(!run||gen!==this.generation)return;
    this.root.querySelector('.mg-focus').hidden=true;this.root.querySelector('.mg-paper-area').hidden=false;this.root.classList.remove('mg-inline');
    await this.player.load(run,run.segments[0]?.panelId);if(gen!==this.generation||!this.visible)return;
    if(this.root.querySelector('[data-field=layout]').value==='scroll')this.root.querySelector(`.mg-paper[data-page-index="${this.pageIndex}"]`)?.scrollIntoView({block:'start'});
    if(play)await this.player.play();
  }
  tick(state){if(!this.root)return;if(this.devices.active)this.app.sessionTracker?.setPlayback({currentTime:state.position/1000,duration:(this.run?.duration_ms||0)/1000,paused:!state.running||!state.segment?.motion});if(this.book&&state.playing&&!this.player.switching&&Date.now()-(this.lastProgressSave||0)>5000){this.lastProgressSave=Date.now();void this.save().catch(()=>{});}const s=this.run===this.player.run?state.segment:null;if(s&&!this.player.switching){if(this.panelId!==s.panelId){this.panelId=s.panelId;this.renderDetails();const panel=this.panel();this.root.querySelector('.mg-panel-title').textContent=panel?.joined?`${this.book.pages[this.pageIndex].label} · Joined panels · ${panel.joined.label}`:`${this.book?.pages[this.pageIndex]?.label} · Panel ${(this.book?.pages[this.pageIndex]?.panels.indexOf(panel)||0)+1}`;const take=this.take();this.root.querySelector('.mg-stage').style.aspectRatio=`${take?.width||1500}/${take?.height||500}`;}
      if(this.root.classList.contains('mg-inline'))this.inlineGeometry();this.bubbleDisplay.draw(s,this.player.video.currentTime,this.settings.bubbles,this.player.currentArtwork,{ignoreTiming:this.settings.ignoreBubbleTiming});
      const still=this.root.querySelector('.mg-still');still.hidden=s.kind!=='still';if(s.kind==='still'&&s.static)still.src=!this.settings.bubbles&&s.staticClean?s.staticClean:s.static;
      const seek=this.root.querySelector('[data-field=seek]');seek.disabled=s.kind==='still'&&s.settings.stillSeconds===0;if(document.activeElement!==seek){seek.max=s.duration;seek.value=Math.max(0,state.position-s.start);}this.root.querySelector('.mg-time').textContent=`${time(state.position-s.start)} / ${time(s.duration)}`;
    }
    this.root.querySelector('[data-action=play]').textContent=state.playing?'❚❚ Pause':state.holding&&s?.kind!=='still'?'↻ Replay':'▶ Play';
    this.root.querySelector('.mg-play-state').textContent=s?.kind==='still'?(s.settings.stillSeconds===0?'Reading · Next to continue':state.holding?'Reading finished · Next to continue':`${s.pageStill?'Still page':'Still panel'} · ${Math.ceil(Math.max(0,s.end-state.position)/1000)}s remaining${state.playing?'':' · paused'}`):this.player.exitAtBoundary?'Finishing motion phrase…':state.holding?'Reading · Next to continue':!state.playing?'Paused':s?.kind==='extension'?'Extending motion':s?.kind==='loop'?`Repeating panel · pass ${s.iteration+1}`:state.playing?(state.running?'Playing':'Buffering…'):'Paused';
    const connected=this.app.handyManager?.connected||this.app.buttplugManager?.connected||this.app.tcodeManager?.connected||this.app.autoblowManager?.connected;this.root.querySelector('.mg-device-state').textContent=this.devices.active?(state.running&&s?.motion?'Devices synced':'Devices prepared · paused'):connected?'Connected · prepare sync':'No device connected';
  }
  inlineGeometry(){const p=this.panel(),t=this.take(),stage=this.root.querySelector('.mg-stage'),focus=this.root.querySelector('.mg-focus');if(!p)return;const [l,top,r,b]=p.bbox;for(const [key,v] of Object.entries({'panel-left':l*100,'panel-top':top*100,'panel-width':(r-l)*100,'panel-height':(b-top)*100}))focus.style.setProperty('--'+key,v+'%');focus.style.setProperty('--panel-mask',p.polygon?'polygon('+p.polygon.map(pt=>`${(pt[0]-l)/(r-l)*100}% ${(pt[1]-top)/(b-top)*100}%`).join(',')+')':'none');const box=t?.transform?.content_box||[0,0,t?.width||1,t?.height||1],width=box[2]-box[0],height=box[3]-box[1];if(width>0&&height>0)for(const [key,v] of Object.entries({'media-x':-box[0]/width*100,'media-y':-box[1]/height*100,'media-width':(t?.width||width)/width*100,'media-height':(t?.height||height)/height*100}))stage.style.setProperty('--'+key,v+'%');}
  async page(index,{guided=false}={}){
    if(!this.book)return;if(!guided)this.cancelTurn();
    const gen=++this.generation;await this.save();if(gen!==this.generation)return;
    this.devices.release();this.player.pause();this.run=null;this.panelId=null;this.pageIndex=Math.max(0,Math.min(index,this.book.pages.length-1));
    const focus=guided&&this.book.pages[this.pageIndex].panels.length>0;
    this.root.querySelector('.mg-focus').hidden=!focus;this.root.querySelector('.mg-paper-area').hidden=!!focus;
    this.root.classList.remove('mg-inline');this.renderPage();this.renderDetails();if(!guided)await this.save();
  }
  async runEnd({advancePage=false}={}){
    const gen=this.generation,playerGen=this.player.generation;await this.save();
    if(gen!==this.generation||playerGen!==this.player.generation||!this.visible)return;
    const next=nextReadingPage(this.book.pages,this.pageIndex);
    if((advancePage||this.settings.autoplay==='continuous')&&next>=0){
      const turn={};this.turningPage=turn;this.transitions.begin();
      try{await this.page(next,{guided:true});if(this.turningPage!==turn)return;await this.startPage();if(this.turningPage===turn){this.transitions.ready();this.turningPage=null;}}
      finally{if(this.turningPage===turn){this.turningPage=null;this.transitions.cancel();}}
    }
    else this.message(next<0?'Book finished.':'Page finished. Continue to the next page when ready.');
  }
  async action(action,button){
    if(action==='open'||action==='open-package')return this.accept(await this.job(action));
    if(action==='cancel')return this.ipc('cancel',{id:this.jobId});
    if(action==='details'){const d=this.root.querySelector('.mg-details');d.hidden=!d.hidden;return;}
    if(action==='connect'){this.app.navBar._onHandyClick?.();return;}
    if(!this.book)return;
    if(action==='refresh'){await this.save();this.player.pause();this.devices.release();return this.accept(await this.job('reopen',{id:this.book.id}));}
    if(action==='export'){await this.save();const r=await this.job('export',{id:this.book.id,options:{alternates:!!this.root.querySelector('[data-field=export-alternates]')?.checked,originalEncodes:!!this.root.querySelector('[data-field=export-encodes]')?.checked}});if(r)this.message(`Exported ${r.path}`);return;}
    if(action==='page')return this.page(Number(button.dataset.index));
    if(action==='next-page'||action==='previous-page'||action==='thumbnail-back'||action==='thumbnail-next')return this.page(this.pageIndex+({'next-page':1,'previous-page':-1,'thumbnail-back':-15,'thumbnail-next':15})[action]);
    if(action==='bookmark'){const id=this.book.pages[this.pageIndex].id;this.bookmarks=this.bookmarks.includes(id)?this.bookmarks.filter(v=>v!==id):[...this.bookmarks,id];this.renderPage();this.renderDetails();return this.save();}
    if(action==='zoom-in'||action==='zoom-out'||action==='fit'){this.zoom=action==='fit'?1:Math.max(.5,Math.min(5,this.zoom*(action==='zoom-in'?1.25:.8)));this.fitGeometry();return this.save();}
    if(action==='fullscreen'){if(document.fullscreenElement)await document.exitFullscreen();else await this.root.requestFullscreen();return;}
    if(action==='bubbles'){const el=this.root.querySelector('[data-field=bubbles]');el.checked=!el.checked;return this.change(el);}
    if(action==='back'){this.cancelTurn();this.generation++;const inline=this.root.classList.contains('mg-inline');this.player.pause();this.root.querySelector('.mg-focus').hidden=true;this.root.querySelector('.mg-paper-area').hidden=false;this.root.classList.remove('mg-inline');if(!inline)this.root.querySelector('.mg-surface').scrollTo(this.returnScroll||{top:0,left:0});return this.save();}
    if(action==='inline'){const inline=this.root.classList.toggle('mg-inline');this.root.querySelector('.mg-paper-area').hidden=!inline;const panel=this.panel();if(panel){this.inlineGeometry();const frame=this.root.querySelector(`.mg-paper[data-page-index="${this.pageIndex}"]`);const focus=this.root.querySelector('.mg-focus');focus.style.setProperty('--panel-top',`${panel.bbox[1]*100}%`);focus.style.setProperty('--panel-height',`${(panel.bbox[3]-panel.bbox[1])*100}%`);focus.style.setProperty('--panel-left',`${panel.bbox[0]*100}%`);focus.style.setProperty('--panel-width',`${(panel.bbox[2]-panel.bbox[0])*100}%`);if(this.root.classList.contains('mg-inline')){frame.append(focus);this.root.querySelector('.mg-surface').scrollTo(this.returnScroll||{top:0,left:0});}else this.root.querySelector('.mg-surface').append(focus);}return;}
    if(action==='play'){if(!this.panelId||!this.run||this.player.run!==this.run){if(this.panel())return this.focusPanel(this.panelId);return this.startPage();}if(this.player.intent)this.player.pause();else await this.player.play();return this.save();}
    if(action==='stop'){this.cancelTurn();this.generation++;this.player.pause();return this.save();}
    if(action==='next-panel'){
      if(!this.run||this.player.run!==this.run)return this.book.pages[this.pageIndex].panels.length?this.startPage():this.page(this.pageIndex+1);
      return this.player.next();
    }
    if(action==='previous-panel'){
      if(!this.book.pages[this.pageIndex].panels.length)return this.page(this.pageIndex-1);
      if(!this.run||this.player.run!==this.run)return this.startPage(false);
      return this.player.previous();
    }
    if(action==='prepare'){const run=await this.ensureRun();if(!run?.scripts.L0.actions.length)throw new Error('This page has no motion scripts. Its animations play without device sync.');if(this.player.run!==run)await this.player.load(run,this.panelId);this.player.pause();if(!await this.devices.arm(run,this.player.wrapper))return;this.message('Device sync prepared. Press Play.');this.tick({segment:this.player.segment,position:this.player.position,playing:false});return;}
    if(action==='export-update'){await this.save();const r=await this.job('export-update',{id:this.book.id});if(r)this.message(`Exported update: ${r.path}`);return;}
    if(action==='apply-update'){await this.save();this.player.pause();this.devices.release();return this.accept(await this.job('apply-update',{id:this.book.id}),{persistCurrent:false});}
    if(action==='rollback-update'){this.player.pause();this.devices.release();return this.accept(await this.ipc('rollback-update',{id:this.book.id}),{persistCurrent:false});}
    if(action==='clean-cache'){const r=await this.ipc('clean-cache');this.message(`Cleared ${(r.bytes/1024/1024).toFixed(1)} MB of unused cache.`);return;}
    if(action==='analyze-audio'){const result=await this.job('analyze-audio',{id:this.book.id,panelId:this.panelId,takeId:this.take()?.id});if(result){this.suggestedGain=result.gain;this.root.querySelector('.mg-audio-suggestion').innerHTML=`<p>Measured average ${result.mean} dB. Suggested gain: ${result.gain}×.</p><button data-action="apply-gain">Apply suggestion</button>`;this.message('Audio suggestion ready; listen before applying.');}return;}
    if(action==='apply-gain'){(this.overrides[this.panelId]||={}).gain=this.suggestedGain;this.invalidate();this.renderDetails();return this.save();}
    if(action==='order-earlier'||action==='order-later'){const panels=this.book.pages[this.pageIndex].panels,index=panels.findIndex(p=>p.id===this.panelId),target=Math.max(0,Math.min(panels.length-1,index+(action==='order-earlier'?-1:1)));const [panel]=panels.splice(index,1);panels.splice(target,0,panel);panels.forEach((p,i)=>(this.overrides[p.id]||={}).order=i);this.invalidate();this.renderPage();return this.save();}
    if(action==='reset-panel'){delete this.overrides[this.panelId];this.invalidate();this.renderDetails();return this.save();}
    if(action==='phrase'){const a=this.root.querySelector('[data-panel-field=phrase-start]').value,b=this.root.querySelector('[data-panel-field=phrase-end]').value;const own=this.overrides[this.panelId]||={};if(a===''&&b==='')delete own.phraseRange;else own.phraseRange=[Number(a)*1000,Number(b)*1000];this.invalidate();return this.save();}
  }
  async change(el){
    if(el.dataset.setting==='ignoreBubbleTiming'){this.settings.ignoreBubbleTiming=el.checked;this.player.notify();return this.save();}
    if(el.dataset.setting){const key=el.dataset.setting;this.settings[key]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;this.invalidate();return this.save();}
    if(el.dataset.panelField&&!el.dataset.panelField.startsWith('phrase')){const key=el.dataset.panelField,own=this.overrides[this.panelId]||={};if(el.value==='')delete own[key];else own[key]=el.type==='number'?Number(el.value):el.value;this.invalidate();return this.save();}
    const field=el.dataset.field;
    if(field==='recent'&&el.value)return this.accept(await this.job('reopen',{id:el.value}));
    if(field==='page')return this.page(Number(el.value)-1);
    if(field==='layout'){this.renderPage();return this.save();}
    if(field==='volume'){this.settings.volume=Number(el.value);this.player.setVolume(this.settings.volume);return this.save();}
    if(field==='bubbles'){this.settings.bubbles=el.checked;await this.player.setBubbles(el.checked);const inline=this.root.classList.contains('mg-inline'),focused=!this.root.querySelector('.mg-focus').hidden;this.renderPage();if(inline)await this.action('inline');else if(focused)this.root.querySelector('.mg-paper-area').hidden=true;return this.save();}
    if(field==='seek'){await this.player.seekPanel(Number(el.value));return this.save();}
  }
}
